# Generated by Django 4.0 on 2022-01-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
